name: instagram
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_database: ^11.1.4
  firebase_remote_config: ^5.1.3
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
